version: '2.2'
services:
  postgres:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=greetings

  greeting_app:
    container_name: greeting_app
    image: nuclear0wl/greetings_app
    environment:
      - DB_URL=postgresql://user:password@database:5432/greetings
    depends_on:
      - postgres

  proxy:
    container_name: proxy
    image: nginx
    ports:
      - "8181:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - greeting_app
